// Exact options recovered from the frozen accounting fixtures. Runtime may only
// change the chronological window and disable final artificial liquidation.
export const C1_FROZEN_OPTIONS = {
  "base": {
    "researchSignalSource": "price-only",
    "independentLifecycle": true,
    "ignoreSignalPositionActions": true,
    "exitOnUniverseRemoval": true,
    "benchmarkSymbols": [
      "SPY",
      "QQQ"
    ],
    "benchmarkCompletionSymbol": null,
    "liquidateAtEnd": true,
    "requireLiquidityPass": true,
    "minimumAverageDollarVolume": 300000000,
    "minimumPrice": 5,
    "slippageBps": 12,
    "commissionPerOrder": 0,
    "requireEntryTimingPass": false,
    "requireTrendAlignment": false,
    "requireRelativeStrength": false,
    "minimumResearchFactorCoverage": 0,
    "blockChaseEntries": false,
    "maxEntryGapPct": 3,
    "selectionMode": "ranked",
    "minimumQualifiedSessions": 1,
    "maxIssuerPositions": 1,
    "classifyStopExits": true,
    "ratchetRiskPlanStop": false,
    "blockedSymbols": [
      "MSTR"
    ],
    "timeStopMaxReturnPct": 1000,
    "timeStopSessions": 252,
    "maxVolatility60Pct": 100,
    "volatilityTargetPct": null,
    "riskBudgetPct": null,
    "baseRankWeight": 0,
    "researchRankMode": "momentum-only",
    "rankedTargetCount": 3,
    "rankedExitBuffer": 6,
    "rankedEntryQueueCount": 9,
    "rankedMinimumHoldSessions": 30,
    "rankedRebalanceSessions": 1,
    "buyTargetPct": 0.33,
    "strongBuyTargetPct": 0.33,
    "buyMaxPositionPct": 0.3333333333333333,
    "strongBuyMaxPositionPct": 0.3333333333333333,
    "buyMaxFactorPct": 1,
    "strongBuyMaxFactorPct": 1,
    "maxPositions": 3,
    "maxSectorPositions": 2,
    "maxSectorPct": 0.5,
    "minimumInitialStopPct": 14,
    "maximumInitialStopPct": 14,
    "pricePatternWeights": {
      "return120Ex20": 0.18,
      "return60Ex5": 0.36,
      "return20": 0.16,
      "return5": -0.12,
      "volatility60Pct": -0.1,
      "alpha60VsSpy": 0.12,
      "alpha60VsQqq": 0.18,
      "controlledPullbackScore": 0.06
    },
    "portfolioDrawdownStopPct": 12,
    "portfolioDrawdownCooldownSessions": 10,
    "initialCapital": 100000,
    "minimumTrade": 750,
    "thesisId": "risk-base",
    "thesisLabel": "base",
    "startDate": "2023-01-04",
    "endDate": "2026-09-01"
  },
  "cooldown15": {
    "researchSignalSource": "price-only",
    "independentLifecycle": true,
    "ignoreSignalPositionActions": true,
    "exitOnUniverseRemoval": true,
    "benchmarkSymbols": [
      "SPY",
      "QQQ"
    ],
    "benchmarkCompletionSymbol": null,
    "liquidateAtEnd": true,
    "requireLiquidityPass": true,
    "minimumAverageDollarVolume": 300000000,
    "minimumPrice": 5,
    "slippageBps": 12,
    "commissionPerOrder": 0,
    "requireEntryTimingPass": false,
    "requireTrendAlignment": false,
    "requireRelativeStrength": false,
    "minimumResearchFactorCoverage": 0,
    "blockChaseEntries": false,
    "maxEntryGapPct": 3,
    "selectionMode": "ranked",
    "minimumQualifiedSessions": 1,
    "maxIssuerPositions": 1,
    "classifyStopExits": true,
    "ratchetRiskPlanStop": false,
    "blockedSymbols": [
      "MSTR"
    ],
    "timeStopMaxReturnPct": 1000,
    "timeStopSessions": 252,
    "maxVolatility60Pct": 100,
    "volatilityTargetPct": null,
    "riskBudgetPct": null,
    "baseRankWeight": 0,
    "researchRankMode": "momentum-only",
    "rankedTargetCount": 3,
    "rankedExitBuffer": 6,
    "rankedEntryQueueCount": 9,
    "rankedMinimumHoldSessions": 30,
    "rankedRebalanceSessions": 1,
    "buyTargetPct": 0.33,
    "strongBuyTargetPct": 0.33,
    "buyMaxPositionPct": 0.3333333333333333,
    "strongBuyMaxPositionPct": 0.3333333333333333,
    "buyMaxFactorPct": 1,
    "strongBuyMaxFactorPct": 1,
    "maxPositions": 3,
    "maxSectorPositions": 2,
    "maxSectorPct": 0.5,
    "minimumInitialStopPct": 14,
    "maximumInitialStopPct": 14,
    "pricePatternWeights": {
      "return120Ex20": 0.18,
      "return60Ex5": 0.36,
      "return20": 0.16,
      "return5": -0.12,
      "volatility60Pct": -0.1,
      "alpha60VsSpy": 0.12,
      "alpha60VsQqq": 0.18,
      "controlledPullbackScore": 0.06
    },
    "portfolioDrawdownStopPct": 12,
    "portfolioDrawdownCooldownSessions": 15,
    "initialCapital": 100000,
    "minimumTrade": 750,
    "thesisId": "risk-cooldown15",
    "thesisLabel": "cooldown15",
    "startDate": "2023-01-04",
    "endDate": "2026-09-01"
  },
  "sector40": {
    "researchSignalSource": "price-only",
    "independentLifecycle": true,
    "ignoreSignalPositionActions": true,
    "exitOnUniverseRemoval": true,
    "benchmarkSymbols": [
      "SPY",
      "QQQ"
    ],
    "benchmarkCompletionSymbol": null,
    "liquidateAtEnd": true,
    "requireLiquidityPass": true,
    "minimumAverageDollarVolume": 300000000,
    "minimumPrice": 5,
    "slippageBps": 12,
    "commissionPerOrder": 0,
    "requireEntryTimingPass": false,
    "requireTrendAlignment": false,
    "requireRelativeStrength": false,
    "minimumResearchFactorCoverage": 0,
    "blockChaseEntries": false,
    "maxEntryGapPct": 3,
    "selectionMode": "ranked",
    "minimumQualifiedSessions": 1,
    "maxIssuerPositions": 1,
    "classifyStopExits": true,
    "ratchetRiskPlanStop": false,
    "blockedSymbols": [
      "MSTR"
    ],
    "timeStopMaxReturnPct": 1000,
    "timeStopSessions": 252,
    "maxVolatility60Pct": 100,
    "volatilityTargetPct": null,
    "riskBudgetPct": null,
    "baseRankWeight": 0,
    "researchRankMode": "momentum-only",
    "rankedTargetCount": 3,
    "rankedExitBuffer": 6,
    "rankedEntryQueueCount": 9,
    "rankedMinimumHoldSessions": 30,
    "rankedRebalanceSessions": 1,
    "buyTargetPct": 0.33,
    "strongBuyTargetPct": 0.33,
    "buyMaxPositionPct": 0.3333333333333333,
    "strongBuyMaxPositionPct": 0.3333333333333333,
    "buyMaxFactorPct": 1,
    "strongBuyMaxFactorPct": 1,
    "maxPositions": 3,
    "maxSectorPositions": 2,
    "maxSectorPct": 0.4,
    "minimumInitialStopPct": 14,
    "maximumInitialStopPct": 14,
    "pricePatternWeights": {
      "return120Ex20": 0.18,
      "return60Ex5": 0.36,
      "return20": 0.16,
      "return5": -0.12,
      "volatility60Pct": -0.1,
      "alpha60VsSpy": 0.12,
      "alpha60VsQqq": 0.18,
      "controlledPullbackScore": 0.06
    },
    "portfolioDrawdownStopPct": 12,
    "portfolioDrawdownCooldownSessions": 10,
    "initialCapital": 100000,
    "minimumTrade": 750,
    "thesisId": "risk-sector40",
    "thesisLabel": "sector40",
    "startDate": "2023-01-04",
    "endDate": "2026-09-01"
  }
};
