// lib/eventRisk.js
// Pre-trade event check plus cross-name material catalyst awareness.
function normalizeSymbol(value){return String(value||"").replace("-", ".").toUpperCase().trim();}
function isoDate(date){return date.toISOString().slice(0,10);}
function addDays(date,days){const next=new Date(date);next.setUTCDate(next.getUTCDate()+days);return next;}
function daysFromToday(dateText){const today=new Date(),a=Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),today.getUTCDate()),d=new Date(`${String(dateText).slice(0,10)}T00:00:00Z`);return Number.isNaN(d.getTime())?null:Math.round((d.getTime()-a)/86400000);}
async function fetchJson(url){const response=await fetch(url);if(!response.ok)throw new Error(`Event-risk request failed: ${response.status}`);return response.json();}
function asArray(value){return Array.isArray(value)?value:value&&typeof value==="object"?[value]:[];}
const KNOWN_DEALS={IRDM:{acquirer:"Rocket Lab",acquirerSymbol:"RKLB",target:"Iridium Communications",announcedDate:"2026-06-28",expectedCloseDate:"2027-06-30",expectedCloseLabel:"mid-2027",referenceValue:54,cashPerShare:27,stockReferenceValue:27,collarLow:67.50,collarHigh:112.50,lowExchangeRatio:.4000,highExchangeRatio:.2400,structure:"$27 cash plus RKLB shares; the stock exchange ratio adjusts inside the $67.50-$112.50 RKLB collar.",source:"Definitive merger agreement"}};
function knownDeal(symbol){return KNOWN_DEALS[normalizeSymbol(symbol)]||null;}
function baseRisk(symbol){const deal=knownDeal(symbol);return{symbol,status:deal?"Blocked":"Clear",label:deal?"Pre-Trade: M&A Event":"Pre-Trade Check: Passed",detail:deal?"This company is subject to a definitive acquisition agreement. Treat it as a deal/spread position rather than a normal standalone fresh-capital setup.":"No near-term earnings, target-company M&A, or material company-news event was found.",blockNewCapital:Boolean(deal),reduceConviction:false,earningsDate:null,daysToEarnings:null,mergerEvent:deal?{...deal}:null,materialCatalysts:[],materialNews:[],checkComplete:true,earningsCheckComplete:true,mergerCheckComplete:Boolean(deal),newsCheckComplete:false,manualCheckRequired:false};}
const FACTOR_BELLWETHERS={"AI Capex & Data Center":["NVDA","AVGO"],"Semiconductor Cycle":["NVDA","AVGO"],"Hardware Cycle":["NVDA"],"AI Networking":["NVDA","AVGO"]};
const AI_CAPEX_EXPOSURE=new Set(["NVDA","AMD","AVGO","ARM","MU","SMCI","DELL","HPE","ANET","MRVL","COHR","DLR","NVT","VRT","ETN","FIX","EME","TER","GEV","PWR","WTS","ORCL"]);
const MACRO_PATTERNS=[{re:/fomc|federal reserve|fed rate|interest rate decision/i,label:"Federal Reserve decision"},{re:/consumer price|\bcpi\b/i,label:"CPI inflation report"},{re:/personal consumption|\bpce\b/i,label:"PCE inflation report"},{re:/nonfarm|employment report|payroll/i,label:"U.S. employment report"}];
const HARD_NEWS_PATTERNS=[
 {re:/\bfda\b.*(recall|early alert|safety|warning)|(?:recall|early alert|safety alert|warning letter).*\bfda\b/i,label:"FDA safety/recall event"},
 {re:/class i recall|serious injur|patient death|fatalit|clinical hold/i,label:"Serious product/clinical safety event"},
 {re:/guidance (?:cut|lowered|reduced|withdrawn)|cuts? (?:full[- ]year )?guidance|withdraws? guidance/i,label:"Guidance reduction"},
 {re:/accounting irregular|restatement|material weakness|auditor resign|fraud/i,label:"Accounting/governance event"},
 {re:/\bsec\b.*(?:investigat|subpoena)|\bdoj\b.*(?:investigat|subpoena)|criminal investig/i,label:"Regulatory/legal investigation"},
 {re:/bankruptcy|chapter 11|going concern/i,label:"Solvency event"}
];
const CAUTION_NEWS_PATTERNS=[
 {re:/product recall|voluntary recall|safety notice/i,label:"Product recall/safety notice"},
 {re:/data breach|cybersecurity incident|ransomware/i,label:"Cybersecurity incident"},
 {re:/lawsuit|litigation|antitrust/i,label:"Material legal development"},
 {re:/secondary offering|public offering|share offering|convertible notes/i,label:"Capital-raising/dilution event"}
];
function eventTiming(row={}){return String(row.time||row.timing||row.when||row.reportTime||row.releaseTime||"").trim();}
function addCatalyst(map,symbol,catalyst){const current=map.get(symbol);if(!current)return;const prior=Array.isArray(current.materialCatalysts)?current.materialCatalysts:[];if(prior.some(x=>x.label===catalyst.label&&x.date===catalyst.date))return;map.set(symbol,{...current,materialCatalysts:[...prior,catalyst]});}
function factorWeights(position={}){return position.factorWeights&&typeof position.factorWeights==="object"?position.factorWeights:{};}
function newsText(row={}){return `${row.title||row.headline||''} ${row.text||row.content||row.summary||''}`.replace(/\s+/g,' ').trim();}
function newsDate(row={}){return String(row.publishedDate||row.date||row.datetime||'').slice(0,10);}
function newsUrl(row={}){return String(row.url||row.link||'');}
function applyNewsRisk(map,row={}){
 const symbol=normalizeSymbol(row.symbol);if(!map.has(symbol))return;
 const text=newsText(row);if(!text)return;
 const hard=HARD_NEWS_PATTERNS.find(x=>x.re.test(text)),caution=!hard&&CAUTION_NEWS_PATTERNS.find(x=>x.re.test(text));if(!hard&&!caution)return;
 const current=map.get(symbol),date=newsDate(row),item={type:'Company News',date,label:(hard||caution).label,title:String(row.title||row.headline||'Material company news').slice(0,240),url:newsUrl(row),material:true,severity:hard?'high':'elevated'};
 const prior=Array.isArray(current.materialNews)?current.materialNews:[];if(prior.some(x=>x.title===item.title&&x.date===item.date))return;
 const detail=hard?`${item.label} detected in recent company news. Do not initiate or add capital until the event is reviewed and the market impact is understood.`:`${item.label} detected in recent company news. Reduce conviction and review the event before using full size.`;
 map.set(symbol,{...current,status:hard?'Blocked':current.status==='Blocked'?'Blocked':'Caution',label:hard?`Pre-Trade: ${item.label}`:current.label==='Pre-Trade Check: Passed'?`Pre-Trade: ${item.label}`:current.label,detail:hard?detail:current.blockNewCapital?current.detail:detail,blockNewCapital:Boolean(current.blockNewCapital||hard),reduceConviction:Boolean(current.reduceConviction||caution),material:true,requiresReview:true,materialNews:[...prior,item],materialCatalysts:[...(current.materialCatalysts||[]),item]});
}
export async function fetchMaterialCatalystMap(positions=[]){const apiKey=process.env.FMP_API_KEY,map=new Map(),today=new Date(),from=isoDate(today),to=isoDate(addDays(today,2)),clean=(positions||[]).map(p=>({symbol:normalizeSymbol(p.symbol||p.ticker),factorWeights:factorWeights(p)})).filter(p=>p.symbol);for(const p of clean)map.set(p.symbol,[]);if(!apiKey||!clean.length)return map;let earnings=[];try{earnings=asArray(await fetchJson(`https://financialmodelingprep.com/stable/earnings-calendar?from=${from}&to=${to}&includeReportTimes=true&apikey=${apiKey}`));}catch{}for(const p of clean){const relevant=[];for(const[factor,weightRaw]of Object.entries(p.factorWeights||{})){const weight=Number(weightRaw)||0;if(weight<.50)continue;const leaders=FACTOR_BELLWETHERS[factor]||[];for(const row of earnings){const leader=normalizeSymbol(row.symbol);if(!leaders.includes(leader)||leader===p.symbol)continue;const days=daysFromToday(row.date);if(days===null||days<0||days>1)continue;relevant.push({type:"Bellwether Earnings",symbol:leader,factor,factorWeight:weight,date:String(row.date).slice(0,10),days,timing:eventTiming(row),label:`${leader} earnings${days===0?" today":" tomorrow"}`,detail:`${leader} is a high-impact bellwether for ${factor}. Its results/guidance can materially change the factor read for ${p.symbol}.`,material:true});}}map.set(p.symbol,relevant);}return map;}
export async function fetchEventRiskMap(symbols=[]){
 const apiKey=process.env.FMP_API_KEY,clean=[...new Set(symbols.map(normalizeSymbol).filter(Boolean))],map=new Map(clean.map(symbol=>[symbol,baseRisk(symbol)]));if(!clean.length)return map;
 if(!apiKey){for(const symbol of clean){const current=map.get(symbol);map.set(symbol,{...current,status:"Manual",label:current.mergerEvent?"Pre-Trade: M&A Event":"Pre-Trade: Manual Check Required",detail:current.mergerEvent?`${current.detail} Earnings, M&A, and company-news verification is incomplete because the market-data API key is unavailable.`:"Event-risk data could not be verified because the market-data API key is unavailable. Do not deploy new capital until earnings, M&A, and major-news risk is manually verified.",blockNewCapital:true,checkComplete:false,earningsCheckComplete:false,mergerCheckComplete:Boolean(current.mergerEvent),newsCheckComplete:false,manualCheckRequired:true});}return map;}
 const now=new Date(),from=isoDate(addDays(now,-2)),to=isoDate(addDays(now,7));let earningsOk=false,mergerOk=false,newsOk=false,earningsRows=[];
 try{earningsRows=asArray(await fetchJson(`https://financialmodelingprep.com/stable/earnings-calendar?from=${from}&to=${to}&includeReportTimes=true&apikey=${apiKey}`));earningsOk=true;for(const row of earningsRows){const symbol=normalizeSymbol(row.symbol);if(!map.has(symbol))continue;const days=daysFromToday(row.date);if(days===null||days< -2||days>7)continue;const current=map.get(symbol),critical=days>=-1&&days<=2,label=days===0?"Earnings Today":days===-1?"Earnings Just Reported":days>0?`Earnings in ${days} day${days===1?"":"s"}`:"Recent Earnings";map.set(symbol,{...current,status:critical?"Blocked":"Caution",label:`Pre-Trade: ${label}`,detail:critical?"Do not initiate new capital until the market has digested the earnings event.":"Near-term earnings risk lowers conviction. A normal partial Buy can remain valid, but a full-size Strong Buy should be reduced until the event passes.",blockNewCapital:critical||Boolean(current.mergerEvent),reduceConviction:!critical&&!current.mergerEvent,earningsDate:String(row.date).slice(0,10),daysToEarnings:days,earningsCheckComplete:true,manualCheckRequired:false});}
   for(const row of earningsRows){const leader=normalizeSymbol(row.symbol),days=daysFromToday(row.date);if(!["NVDA","AVGO"].includes(leader)||days===null||days<0||days>1)continue;for(const target of clean){if(target===leader||!AI_CAPEX_EXPOSURE.has(target))continue;addCatalyst(map,target,{type:"Bellwether Earnings",symbol:leader,factor:"AI Capex & Data Center",date:String(row.date).slice(0,10),days,timing:eventTiming(row),label:`${leader} earnings${days===0?" today":" tomorrow"}`,detail:`${leader} is a high-impact bellwether for AI infrastructure demand. Its results and guidance can materially change the factor read for ${target}.`,material:true});}}
 }catch{earningsOk=false;}
 try{const econ=asArray(await fetchJson(`https://financialmodelingprep.com/stable/economic-calendar?from=${isoDate(now)}&to=${isoDate(addDays(now,1))}&apikey=${apiKey}`));for(const row of econ){const text=`${row.event||row.name||row.title||""} ${row.country||""}`,match=MACRO_PATTERNS.find(x=>x.re.test(text)),days=daysFromToday(row.date);if(!match||days===null||days<0||days>1)continue;for(const target of clean)addCatalyst(map,target,{type:"Macro",date:String(row.date).slice(0,10),days,timing:eventTiming(row),label:`${match.label}${days===0?" today":" tomorrow"}`,detail:`Scheduled ${match.label} can materially change market risk appetite; separate that factor move from stock-specific evidence.`,material:true});}}catch{}
 try{const rows=asArray(await fetchJson(`https://financialmodelingprep.com/stable/mergers-acquisitions-latest?page=0&limit=1000&apikey=${apiKey}`));mergerOk=true;for(const row of rows){const target=normalizeSymbol(row.targetedSymbol);if(!map.has(target))continue;const current=map.get(target),known=knownDeal(target);map.set(target,{...current,status:"Blocked",label:"Pre-Trade: M&A Event",detail:"This company appears as an acquisition target. Treat it as an event/deal trade rather than a normal fresh-capital setup.",blockNewCapital:true,reduceConviction:false,mergerEvent:known?{...known}:{acquirer:row.companyName||row.symbol||"Acquirer",target:row.targetedCompanyName||target,transactionDate:row.transactionDate||null},mergerCheckComplete:true,manualCheckRequired:false});}}catch{mergerOk=false;}
 try{const newsFrom=isoDate(addDays(now,-2)),newsTo=isoDate(now),joined=clean.map(s=>s.replace('.','-')).join(','),rows=asArray(await fetchJson(`https://financialmodelingprep.com/stable/news/stock?symbols=${encodeURIComponent(joined)}&from=${newsFrom}&to=${newsTo}&limit=500&apikey=${apiKey}`));newsOk=true;for(const row of rows)applyNewsRisk(map,row);for(const symbol of clean){const current=map.get(symbol);map.set(symbol,{...current,newsCheckComplete:true});}}catch{newsOk=false;}
 for(const symbol of clean){const current=map.get(symbol),known=Boolean(current.mergerEvent&&knownDeal(symbol));if(current.blockNewCapital&&current.mergerEvent){map.set(symbol,{...current,checkComplete:earningsOk&&(mergerOk||known)&&newsOk,earningsCheckComplete:earningsOk,mergerCheckComplete:mergerOk||known,newsCheckComplete:newsOk,manualCheckRequired:!earningsOk||!newsOk});continue;}if(current.blockNewCapital&&current.requiresReview){map.set(symbol,{...current,checkComplete:earningsOk&&(mergerOk||known)&&newsOk,earningsCheckComplete:earningsOk,mergerCheckComplete:mergerOk||known,newsCheckComplete:newsOk,manualCheckRequired:false});continue;}if(current.blockNewCapital)continue;if(!earningsOk||(!mergerOk&&!known)||!newsOk){map.set(symbol,{...current,status:"Manual",label:"Pre-Trade: Manual Check Required",detail:"Automated event-risk verification was incomplete. Do not deploy new capital until earnings, M&A, and major-news risk is manually verified.",blockNewCapital:true,checkComplete:false,earningsCheckComplete:earningsOk,mergerCheckComplete:mergerOk||known,newsCheckComplete:newsOk,manualCheckRequired:true});continue;}map.set(symbol,{...current,checkComplete:true,earningsCheckComplete:true,mergerCheckComplete:true,newsCheckComplete:true});}return map;
}
export function applyEventRiskGate(stock={},eventRisk=null){const risk=eventRisk||{status:"Manual",label:"Pre-Trade: Manual Check Required",detail:"Event-risk data was unavailable. Do not deploy new capital until earnings, M&A, and major-news risk is manually verified.",blockNewCapital:true,reduceConviction:false,checkComplete:false,manualCheckRequired:true,materialCatalysts:[]},rec=stock.recommendation&&typeof stock.recommendation==="object"?stock.recommendation:{},current=String(rec.label||stock.action||"Avoid");let action=current;if(risk.blockNewCapital&&["Strong Buy","Buy"].includes(current))action="Watch";else if(risk.reduceConviction&&current==="Strong Buy")action="Buy";const downgraded=action!==current;let decisionWhy=rec.decisionWhy||rec.actionSummary||"";if(risk.mergerEvent)decisionWhy=`${risk.detail} New capital is blocked because standalone upside is no longer the correct decision framework.`;else if(risk.blockNewCapital&&downgraded)decisionWhy=`${risk.detail} Keep the setup on Watch until the event clears or verification is completed.`;else if(risk.reduceConviction&&downgraded)decisionWhy=`${risk.detail} Use partial size only until the event passes.`;else if(risk.manualCheckRequired&&["Strong Buy","Buy"].includes(current))decisionWhy=`${decisionWhy||"Actionable candidate."} Manual event verification is required before execution.`;return{...stock,action,eventRisk:risk,preTradeCheck:risk,materialCatalysts:risk.materialCatalysts||[],recommendation:{...rec,label:action,displayLabel:action,recommendation:action,tradeAction:action,decisionTiming:["Strong Buy","Buy"].includes(action)?"Now":"Wait for Trigger",positionSize:action==="Strong Buy"?"Full":action==="Buy"?"Partial":"None",decisionWhy,actionSummary:decisionWhy,blockedBuyNow:risk.blockNewCapital&&downgraded,blockedReason:risk.blockNewCapital?risk.detail:"",eventRisk:risk,preTradeCheck:risk}};}
