// R15 returns the research program to a momentum spine.  The definitions in
// this file are intentionally frozen as a bounded candidate family before any
// R15 result is calculated.  They use only close-known price/volume features
// already present in the point-in-time S&P 500 replay.

const common = Object.freeze({
  researchSignalSource: "price-only",
  independentLifecycle: true,
  ignoreSignalPositionActions: true,
  benchmarkSymbols: ["SPY", "QQQ"],
  benchmarkCompletionSymbol: null,
  liquidateAtEnd: true,
  requireLiquidityPass: true,
  minimumAverageDollarVolume: 30_000_000,
  minimumPrice: 5,
  slippageBps: 12,
  commissionPerOrder: 0,
  requireEntryTimingPass: false,
  requireTrendAlignment: false,
  requireRelativeStrength: false,
  minimumResearchFactorCoverage: 0,
  blockChaseEntries: false,
  maxEntryGapPct: 3,
  selectionMode: "ranked",
  researchRankMode: "momentum-spine",
  rankedEntryQueueCount: 30,
  minimumQualifiedSessions: 1,
  minimumInitialStopPct: 18,
  maximumInitialStopPct: 18,
  maxIssuerPositions: 1,
  classifyStopExits: true,
  ratchetRiskPlanStop: false,
  timeStopMaxReturnPct: 1_000,
  maxVolatility60Pct: 80,
  volatilityTargetPct: null,
  riskBudgetPct: null,
  baseRankWeight: 0,
});

function candidate({ researchGeneration, id, label, family, mechanism, weights, lifecycle, filters = {} }) {
  const targetPct = 0.99 / lifecycle.target;
  return {
    id,
    researchGeneration,
    label,
    family,
    mechanism,
    weights,
    lifecycle,
    control: false,
    overrides: {
      ...common,
      ...filters,
      momentumSpineWeights: weights,
      rankedRebalanceSessions: lifecycle.rebalance,
      rankedTargetCount: lifecycle.target,
      rankedExitBuffer: lifecycle.exitBuffer,
      rankedMinimumHoldSessions: lifecycle.minimumHold,
      rankedEntryQueueCount: lifecycle.target * 3,
      buyTargetPct: targetPct,
      strongBuyTargetPct: targetPct,
      buyMaxPositionPct: 1 / lifecycle.target,
      strongBuyMaxPositionPct: 1 / lifecycle.target,
      buyMaxFactorPct: 1,
      strongBuyMaxFactorPct: 1,
      maxPositions: lifecycle.target,
      maxSectorPositions: lifecycle.maxSectorPositions,
      maxSectorPct: lifecycle.maxSectorPct,
      timeStopSessions: lifecycle.timeStop,
    },
  };
}

export function pointInTimeMomentumSpineR15Definitions() {
  return [
    candidate({
      researchGeneration: "R15",
      id: "r15-persistent-dual-benchmark-leaders",
      label: "Persistent dual-benchmark momentum leaders",
      family: "persistent-leadership",
      mechanism:
        "intermediate momentum that persists versus both SPY and QQQ and arrives through a continuous price path",
      weights: {
        momentum: 0.2,
        relative120: 0.28,
        relative60: 0.17,
        continuity: 0.15,
        anchor: 0.08,
        contraction: 0.05,
        stability: 0.04,
        shortRunRestraint: 0.03,
      },
      lifecycle: {
        target: 6,
        rebalance: 10,
        exitBuffer: 10,
        minimumHold: 20,
        timeStop: 126,
        maxSectorPositions: 4,
        maxSectorPct: 0.67,
      },
    }),
    candidate({
      researchGeneration: "R16",
      id: "r15-pullback-reacceleration",
      label: "Momentum pullback and reacceleration",
      family: "reacceleration",
      mechanism:
        "established relative leaders are entered after a controlled pause only when near-term momentum begins accelerating again",
      weights: {
        momentum: 0.2,
        relative120: 0.2,
        relative60: 0.15,
        continuity: 0.1,
        pullback: 0.13,
        reacceleration: 0.12,
        technical: 0.07,
        shortRunRestraint: 0.03,
      },
      lifecycle: {
        target: 8,
        rebalance: 5,
        exitBuffer: 13,
        minimumHold: 10,
        timeStop: 63,
        maxSectorPositions: 5,
        maxSectorPct: 0.63,
      },
    }),
    candidate({
      researchGeneration: "R17",
      id: "r15-volume-confirmed-momentum",
      label: "Volume-confirmed momentum leadership",
      family: "institutional-participation",
      mechanism:
        "persistent leadership receives additional rank only when current participation and trend structure confirm demand",
      weights: {
        momentum: 0.2,
        relative120: 0.22,
        relative60: 0.14,
        continuity: 0.12,
        anchor: 0.08,
        volumeConfirmation: 0.1,
        technical: 0.08,
        contraction: 0.04,
        shortRunRestraint: 0.02,
      },
      lifecycle: {
        target: 8,
        rebalance: 5,
        exitBuffer: 13,
        minimumHold: 15,
        timeStop: 84,
        maxSectorPositions: 5,
        maxSectorPct: 0.63,
      },
    }),
    candidate({
      researchGeneration: "R18",
      id: "r15-volatility-contraction-leaders",
      label: "Volatility-contraction momentum leaders",
      family: "trend-template",
      mechanism:
        "strong medium-term leaders with a tightening short-term volatility profile are favored before renewed expansion",
      weights: {
        momentum: 0.2,
        relative120: 0.25,
        relative60: 0.15,
        continuity: 0.12,
        anchor: 0.08,
        contraction: 0.12,
        stability: 0.05,
        technical: 0.03,
      },
      lifecycle: {
        target: 8,
        rebalance: 10,
        exitBuffer: 14,
        minimumHold: 20,
        timeStop: 126,
        maxSectorPositions: 5,
        maxSectorPct: 0.63,
      },
      filters: { requireTrendAlignment: true },
    }),
    candidate({
      researchGeneration: "R19",
      id: "r15-slow-runner-retention",
      label: "Slow momentum with runner retention",
      family: "runner-retention",
      mechanism:
        "concentrated persistent leaders are held through ordinary volatility so rank churn does not cut durable winners short",
      weights: {
        momentum: 0.18,
        relative120: 0.32,
        relative60: 0.12,
        continuity: 0.18,
        anchor: 0.1,
        stability: 0.04,
        contraction: 0.03,
        shortRunRestraint: 0.03,
      },
      lifecycle: {
        target: 6,
        rebalance: 20,
        exitBuffer: 12,
        minimumHold: 40,
        timeStop: 252,
        maxSectorPositions: 5,
        maxSectorPct: 0.84,
      },
      filters: {
        minimumInitialStopPct: 22,
        maximumInitialStopPct: 22,
      },
    }),
  ];
}

export function pointInTimeMomentumSpineR15Controls() {
  const matched = {
    ...common,
    rankedRebalanceSessions: 10,
    rankedTargetCount: 8,
    rankedExitBuffer: 14,
    rankedMinimumHoldSessions: 20,
    rankedEntryQueueCount: 24,
    buyTargetPct: 0.12375,
    strongBuyTargetPct: 0.12375,
    buyMaxPositionPct: 0.125,
    strongBuyMaxPositionPct: 0.125,
    buyMaxFactorPct: 1,
    strongBuyMaxFactorPct: 1,
    maxPositions: 8,
    maxSectorPositions: 5,
    maxSectorPct: 0.63,
    timeStopSessions: 126,
  };
  return [
    {
      id: "r15-control-simple-momentum",
      label: "Simple momentum matched-lifecycle control",
      family: "control",
      mechanism: "unmodified cross-sectional momentum under the matched lifecycle",
      weights: { momentum: 1 },
      control: true,
      overrides: { ...matched, researchRankMode: "momentum-only" },
    },
    {
      id: "r15-control-random-seed-15",
      label: "Random matched-lifecycle control",
      family: "control",
      mechanism: "deterministic random ranking under the matched lifecycle",
      weights: { random: 1 },
      control: true,
      overrides: {
        ...matched,
        researchRankMode: "random-placebo",
        researchRandomSeed: 15,
      },
    },
  ];
}
