// R20-R24 move the successful R19 runner-retention lifecycle into the
// point-in-time Nasdaq index universe. Definitions are frozen together before
// any result is calculated. They use only close-known price/volume features.

const common = Object.freeze({
  researchSignalSource: "price-only",
  independentLifecycle: true,
  ignoreSignalPositionActions: true,
  exitOnUniverseRemoval: true,
  benchmarkSymbols: ["SPY", "QQQ"],
  benchmarkCompletionSymbol: null,
  liquidateAtEnd: true,
  requireLiquidityPass: true,
  minimumAverageDollarVolume: 30_000_000,
  minimumPrice: 5,
  slippageBps: 12,
  commissionPerOrder: 0,
  requireEntryTimingPass: false,
  requireTrendAlignment: false,
  requireRelativeStrength: false,
  minimumResearchFactorCoverage: 0,
  blockChaseEntries: false,
  maxEntryGapPct: 3,
  selectionMode: "ranked",
  researchRankMode: "momentum-spine",
  rankedEntryQueueCount: 18,
  minimumQualifiedSessions: 1,
  maxIssuerPositions: 1,
  classifyStopExits: true,
  ratchetRiskPlanStop: false,
  timeStopMaxReturnPct: 1_000,
  maxVolatility60Pct: 100,
  volatilityTargetPct: null,
  riskBudgetPct: null,
  baseRankWeight: 0,
});

function candidate({
  researchGeneration,
  id,
  label,
  mechanism,
  weights,
  target,
  rebalance,
  exitBuffer,
  minimumHold,
  timeStop,
  stopPct,
}) {
  const targetPct = 0.99 / target;
  return {
    id,
    researchGeneration,
    label,
    family: "nasdaq-runner-retention",
    mechanism,
    weights,
    lifecycle: {
      target,
      rebalance,
      exitBuffer,
      minimumHold,
      timeStop,
      stopPct,
    },
    control: false,
    overrides: {
      ...common,
      momentumSpineWeights: weights,
      rankedRebalanceSessions: rebalance,
      rankedTargetCount: target,
      rankedExitBuffer: exitBuffer,
      rankedMinimumHoldSessions: minimumHold,
      rankedEntryQueueCount: target * 3,
      buyTargetPct: targetPct,
      strongBuyTargetPct: targetPct,
      buyMaxPositionPct: 1 / target,
      strongBuyMaxPositionPct: 1 / target,
      buyMaxFactorPct: 1,
      strongBuyMaxFactorPct: 1,
      maxPositions: target,
      // Historical sector labels are unavailable in the Nasdaq dataset.
      maxSectorPositions: target,
      maxSectorPct: 1,
      minimumInitialStopPct: stopPct,
      maximumInitialStopPct: stopPct,
      timeStopSessions: timeStop,
    },
  };
}

export function pointInTimeNasdaqRunnerDefinitions() {
  return [
    candidate({
      researchGeneration: "R20",
      id: "r20-r19-nasdaq-replication",
      label: "R19 runner retention replicated in Nasdaq",
      mechanism:
        "tests whether R19's persistent-leader lifecycle transfers unchanged to the benchmark-aligned Nasdaq universe",
      weights: {
        momentum: 0.18,
        relative120: 0.32,
        relative60: 0.12,
        continuity: 0.18,
        anchor: 0.1,
        stability: 0.04,
        contraction: 0.03,
        shortRunRestraint: 0.03,
      },
      target: 6,
      rebalance: 20,
      exitBuffer: 12,
      minimumHold: 40,
      timeStop: 252,
      stopPct: 22,
    }),
    candidate({
      researchGeneration: "R21",
      id: "r21-concentrated-persistent-runners",
      label: "Concentrated persistent Nasdaq runners",
      mechanism:
        "three highest-persistence leaders retain enough weight to compete with a concentrated benchmark",
      weights: {
        momentum: 0.15,
        relative120: 0.38,
        relative60: 0.12,
        continuity: 0.2,
        anchor: 0.1,
        stability: 0.03,
        contraction: 0.02,
      },
      target: 3,
      rebalance: 20,
      exitBuffer: 7,
      minimumHold: 40,
      timeStop: 252,
      stopPct: 25,
    }),
    candidate({
      researchGeneration: "R22",
      id: "r22-quarterly-runner-retention",
      label: "Quarterly Nasdaq runner retention",
      mechanism:
        "quarterly review minimizes rank churn and permits durable leadership compounding",
      weights: {
        momentum: 0.12,
        relative120: 0.4,
        relative60: 0.08,
        continuity: 0.2,
        anchor: 0.12,
        stability: 0.05,
        contraction: 0.03,
      },
      target: 4,
      rebalance: 63,
      exitBuffer: 9,
      minimumHold: 63,
      timeStop: 378,
      stopPct: 28,
    }),
    candidate({
      researchGeneration: "R23",
      id: "r23-dual-speed-continuation",
      label: "Dual-speed Nasdaq continuation",
      mechanism:
        "medium- and shorter-horizon benchmark leadership must agree while continuity keeps one-week noise from forcing exits",
      weights: {
        momentum: 0.15,
        relative120: 0.28,
        relative60: 0.2,
        continuity: 0.17,
        anchor: 0.08,
        stability: 0.05,
        contraction: 0.04,
        shortRunRestraint: 0.03,
      },
      target: 4,
      rebalance: 20,
      exitBuffer: 9,
      minimumHold: 40,
      timeStop: 252,
      stopPct: 25,
    }),
    candidate({
      researchGeneration: "R24",
      id: "r24-anchored-continuous-runners",
      label: "52-week-high anchored Nasdaq runners",
      mechanism:
        "leaders near long-run highs with continuous paths receive more weight than abrupt short-run spikes",
      weights: {
        momentum: 0.16,
        relative120: 0.28,
        relative60: 0.1,
        continuity: 0.18,
        anchor: 0.16,
        stability: 0.05,
        contraction: 0.04,
        shortRunRestraint: 0.03,
      },
      target: 5,
      rebalance: 20,
      exitBuffer: 11,
      minimumHold: 40,
      timeStop: 252,
      stopPct: 25,
    }),
  ];
}

export function pointInTimeNasdaqRunnerControls() {
  const target = 6;
  const matched = {
    ...common,
    rankedRebalanceSessions: 20,
    rankedTargetCount: target,
    rankedExitBuffer: 12,
    rankedMinimumHoldSessions: 40,
    rankedEntryQueueCount: 18,
    buyTargetPct: 0.99 / target,
    strongBuyTargetPct: 0.99 / target,
    buyMaxPositionPct: 1 / target,
    strongBuyMaxPositionPct: 1 / target,
    buyMaxFactorPct: 1,
    strongBuyMaxFactorPct: 1,
    maxPositions: target,
    maxSectorPositions: target,
    maxSectorPct: 1,
    minimumInitialStopPct: 22,
    maximumInitialStopPct: 22,
    timeStopSessions: 252,
  };
  return [
    {
      id: "r20-control-simple-momentum",
      label: "Simple Nasdaq momentum matched-lifecycle control",
      family: "control",
      mechanism: "unmodified momentum under R20's matched runner lifecycle",
      weights: { momentum: 1 },
      control: true,
      overrides: { ...matched, researchRankMode: "momentum-only" },
    },
    {
      id: "r20-control-random-seed-20",
      label: "Random Nasdaq matched-lifecycle control",
      family: "control",
      mechanism: "deterministic random ranking under R20's matched runner lifecycle",
      weights: { random: 1 },
      control: true,
      overrides: {
        ...matched,
        researchRankMode: "random-placebo",
        researchRandomSeed: 20,
      },
    },
  ];
}
