// R35-R39 are frozen before execution. They test a distinct mechanism exposed
// by R30-R34: leadership must be refreshed more quickly when Nasdaq momentum
// breadth weakens, while persistent runners should rotate slowly in broad
// regimes. Position count and cadence use only contemporaneous cross-sectional
// information. Cash remains cash and folds never reset the portfolio.

const persistentWeights = Object.freeze({
  momentum: 0.15,
  relative120: 0.38,
  relative60: 0.12,
  continuity: 0.2,
  anchor: 0.1,
  stability: 0.03,
  contraction: 0.02,
});

const common = Object.freeze({
  researchSignalSource: "price-only",
  independentLifecycle: true,
  ignoreSignalPositionActions: true,
  exitOnUniverseRemoval: true,
  benchmarkSymbols: ["SPY", "QQQ"],
  benchmarkCompletionSymbol: null,
  liquidateAtEnd: true,
  requireLiquidityPass: true,
  minimumAverageDollarVolume: 30_000_000,
  minimumPrice: 5,
  slippageBps: 12,
  commissionPerOrder: 0,
  requireEntryTimingPass: false,
  requireTrendAlignment: false,
  requireRelativeStrength: false,
  minimumResearchFactorCoverage: 0,
  blockChaseEntries: false,
  maxEntryGapPct: 3,
  selectionMode: "ranked",
  researchRankMode: "momentum-spine",
  minimumQualifiedSessions: 1,
  maxIssuerPositions: 1,
  classifyStopExits: true,
  ratchetRiskPlanStop: false,
  timeStopMaxReturnPct: 1_000,
  maxVolatility60Pct: 100,
  riskBudgetPct: null,
  baseRankWeight: 0,
  rankedAdaptiveRebalanceEnabled: true,
  rankedAdaptiveEqualWeightEnabled: true,
  timeStopSessions: 504,
});

function candidate({ researchGeneration, id, label, mechanism, weakTarget, strongTarget, weakCadence, strongCadence, threshold, minimumHold, exitBuffer, stopPct, volatilityTargetPct = null, weights = persistentWeights }) {
  return {
    id,
    researchGeneration,
    label,
    family: "breadth-adaptive-nasdaq-runner",
    mechanism,
    weights,
    control: false,
    overrides: {
      ...common,
      momentumSpineWeights: weights,
      rankedRebalanceSessions: strongCadence,
      rankedWeakBreadthThresholdPct: threshold,
      rankedWeakBreadthRebalanceSessions: weakCadence,
      rankedStrongBreadthRebalanceSessions: strongCadence,
      rankedAdaptiveTargetEnabled: weakTarget !== strongTarget,
      rankedWeakBreadthTargetCount: weakTarget,
      rankedStrongBreadthTargetCount: strongTarget,
      rankedTargetCount: strongTarget,
      rankedExitBuffer: exitBuffer,
      rankedMinimumHoldSessions: minimumHold,
      rankedEntryQueueCount: Math.max(12, strongTarget * 4),
      buyTargetPct: 0.99 / strongTarget,
      strongBuyTargetPct: 0.99 / strongTarget,
      buyMaxPositionPct: 1,
      strongBuyMaxPositionPct: 1,
      buyMaxFactorPct: 1,
      strongBuyMaxFactorPct: 1,
      maxPositions: strongTarget,
      maxSectorPositions: strongTarget,
      maxSectorPct: 1,
      minimumInitialStopPct: stopPct,
      maximumInitialStopPct: stopPct,
      volatilityTargetPct,
    },
  };
}

export function pointInTimeNasdaqAdaptiveRunnerDefinitions() {
  return [
    candidate({
      researchGeneration: "R35",
      id: "r35-breadth-adaptive-one-three",
      label: "Breadth-adaptive one-to-three leaders",
      mechanism: "concentrates in the strongest leader and refreshes twice monthly when breadth is weak; holds three leaders monthly when breadth is broad",
      weakTarget: 1,
      strongTarget: 3,
      weakCadence: 10,
      strongCadence: 20,
      threshold: 50,
      minimumHold: 20,
      exitBuffer: 8,
      stopPct: 22,
    }),
    candidate({
      researchGeneration: "R36",
      id: "r36-breadth-adaptive-two-four",
      label: "Breadth-adaptive two-to-four leaders",
      mechanism: "uses two leaders in narrow regimes and four in broad regimes to reduce idiosyncratic drawdown",
      weakTarget: 2,
      strongTarget: 4,
      weakCadence: 10,
      strongCadence: 20,
      threshold: 50,
      minimumHold: 20,
      exitBuffer: 10,
      stopPct: 22,
    }),
    candidate({
      researchGeneration: "R37",
      id: "r37-severe-narrowness-refresh",
      label: "Severe-narrowness rapid refresh",
      mechanism: "switches to one leader and weekly review only below 45% breadth; otherwise retains two leaders monthly",
      weakTarget: 1,
      strongTarget: 2,
      weakCadence: 5,
      strongCadence: 20,
      threshold: 45,
      minimumHold: 10,
      exitBuffer: 5,
      stopPct: 18,
    }),
    candidate({
      researchGeneration: "R38",
      id: "r38-two-leader-adaptive-cadence",
      label: "Two leaders with adaptive cadence",
      mechanism: "isolates faster weak-breadth rotation while holding concentration fixed at two names",
      weakTarget: 2,
      strongTarget: 2,
      weakCadence: 5,
      strongCadence: 20,
      threshold: 50,
      minimumHold: 10,
      exitBuffer: 6,
      stopPct: 20,
    }),
    candidate({
      researchGeneration: "R39",
      id: "r39-dual-speed-three-leader",
      label: "Dual-speed three-leader transition",
      mechanism: "raises recent relative strength during leadership transitions and uses a 24% volatility budget",
      weakTarget: 3,
      strongTarget: 3,
      weakCadence: 5,
      strongCadence: 20,
      threshold: 50,
      minimumHold: 10,
      exitBuffer: 8,
      stopPct: 20,
      volatilityTargetPct: 24,
      weights: {
        momentum: 0.12,
        relative120: 0.28,
        relative60: 0.28,
        continuity: 0.14,
        anchor: 0.1,
        stability: 0.04,
        contraction: 0.04,
      },
    }),
  ];
}

export function pointInTimeNasdaqAdaptiveRunnerControls() {
  const matched = {
    ...common,
    rankedWeakBreadthThresholdPct: 50,
    rankedWeakBreadthRebalanceSessions: 10,
    rankedStrongBreadthRebalanceSessions: 20,
    rankedAdaptiveTargetEnabled: true,
    rankedWeakBreadthTargetCount: 2,
    rankedStrongBreadthTargetCount: 4,
    rankedTargetCount: 4,
    rankedExitBuffer: 10,
    rankedMinimumHoldSessions: 20,
    rankedEntryQueueCount: 16,
    buyTargetPct: 0.2475,
    strongBuyTargetPct: 0.2475,
    buyMaxPositionPct: 1,
    strongBuyMaxPositionPct: 1,
    buyMaxFactorPct: 1,
    strongBuyMaxFactorPct: 1,
    maxPositions: 4,
    maxSectorPositions: 4,
    maxSectorPct: 1,
    minimumInitialStopPct: 22,
    maximumInitialStopPct: 22,
  };
  return [
    {
      id: "r35-control-simple-momentum",
      label: "Breadth-adaptive simple momentum control",
      family: "control",
      mechanism: "simple momentum under the matched adaptive lifecycle",
      weights: { momentum: 1 },
      control: true,
      overrides: { ...matched, researchRankMode: "momentum-only" },
    },
    {
      id: "r35-control-random-seed-35",
      label: "Breadth-adaptive random control",
      family: "control",
      mechanism: "deterministic random ranking under the matched adaptive lifecycle",
      weights: { random: 1 },
      control: true,
      overrides: {
        ...matched,
        researchRankMode: "random-placebo",
        researchRandomSeed: 35,
      },
    },
  ];
}
