// R53 concentrated five-session neighborhood.
const c=Object.freeze({researchSignalSource:"price-only",independentLifecycle:true,ignoreSignalPositionActions:true,exitOnUniverseRemoval:true,benchmarkSymbols:["SPY","QQQ"],benchmarkCompletionSymbol:null,liquidateAtEnd:true,requireLiquidityPass:true,minimumAverageDollarVolume:30_000_000,minimumPrice:5,slippageBps:12,commissionPerOrder:0,requireEntryTimingPass:false,requireTrendAlignment:false,requireRelativeStrength:false,minimumResearchFactorCoverage:0,blockChaseEntries:false,maxEntryGapPct:3,selectionMode:"ranked",minimumQualifiedSessions:1,maxIssuerPositions:1,classifyStopExits:true,ratchetRiskPlanStop:false,timeStopMaxReturnPct:1_000,timeStopSessions:252,maxVolatility60Pct:100,volatilityTargetPct:null,riskBudgetPct:null,basestehendenRankWeight:0});
const w={momentum:.08,longMomentum:.14,mediumMomentum:.12,shortMomentum:.04,veryShortMomentum:0,relativeStrength:.3,stability:.06,lowVolatility:.06,technical:.04,pullback:.03,liquidity:.03};
function d(key,hold,reb,buf,stop=18){return{key,hold,reb,buf,stop};}
export function pointInTimeNasdaqDistinctAlphaDefinitions(){
 const v=[d("reb3",20,3,6),d("reb4",20,4,6),d("reb5",20,5,6),d("reb6",20,6,6),d("reb7",20,7,6),d("hold15",15,5,6),d("hold25",25,5,6),d("buffer5",20,5,5),d("buffer7",20,5,7),d("stop16",20,5,6,16)];
 return v.map((x,i)=>{const g=45+i,target=3;return{id:`r${g}-r53n-${x.key}`,researchGeneration:`R${g}`,label:`R53 neighborhood ${x.key}`,family:"r53-five-day-neighborhood",mechanism:"Three-position multi-horizon leadership neighborhood",control:false,overrides:{...c,baseRankWeight:0,rankedTargetCount:target,rankedExitBuffer:x.buf,rankedEntryQueueCount:9,rankedMinimumHoldSessions:x.hold,rankedRebalanceSessions:x.reb,buyTargetPct:.33,strongBuyTargetPct:.33,buyMaxPositionPct:1/3,strongBuyMaxPositionPct:1/3,buyMaxFactorPct:1,strongBuyMaxFactorPct:1,maxPositions:3,maxSectorPositions:3,maxSectorPct:1,minimumInitialStopPct:x.stop,maximumInitialStopPct:x.stop,researchRankMode:"multi-horizon-price-alpha",priceAlphaWeights:w}};});
}
export function pointInTimeNasdaqDistinctAlphaControls(){const m={...c,baseRankWeight:0,rankedTargetCount:3,rankedExitBuffer:6,rankedEntryQueueCount:9,rankedMinimumHoldSessions:20,rankedRebalanceSessions:5,buyTargetPct:.33,strongBuyTargetPct:.33,buyMaxPositionPct:1/3,strongBuyMaxPositionPct:1/3,buyMaxFactorPct:1,strongBuyMaxFactorPct:1,maxPositions:3,maxSectorPositions:3,maxSectorPct:1,minimumInitialStopPct:18,maximumInitialStopPct:18};return[{id:"r45-control-momentum",label:"Matched simple momentum",family:"control",control:true,overrides:{...m,researchRankMode:"momentum-only"}},{id:"r45-control-random",label:"Matched random ranking",family:"control",control:true,overrides:{...m,researchRankMode:"random-placebo",researchRandomSeed:45}}];}
