const CASH=new Set(['CASH','SWVXX','VMFXX','SPAXX','FDRXX','MMF']);

// Portfolio risk factors are intentionally economic exposures, not GICS sectors.
// A security may load on more than one factor; weights sum to 1 for known overrides.
const FACTOR_OVERRIDES={
  NVDA:{'AI Capex & Data Center':.85,'Semiconductor Cycle':.15},AMD:{'AI Capex & Data Center':.75,'Semiconductor Cycle':.25},AVGO:{'AI Capex & Data Center':.75,'Semiconductor Cycle':.25},ARM:{'AI Capex & Data Center':.70,'Semiconductor Cycle':.30},MU:{'AI Capex & Data Center':.80,'Semiconductor Cycle':.20},SMCI:{'AI Capex & Data Center':.90,'Hardware Cycle':.10},DELL:{'AI Capex & Data Center':.80,'Hardware Cycle':.20},HPE:{'AI Capex & Data Center':.70,'Hardware Cycle':.30},ANET:{'AI Capex & Data Center':.80,'Networking':.20},MRVL:{'AI Capex & Data Center':.75,'Semiconductor Cycle':.25},COHR:{'AI Capex & Data Center':.70,'Optical Networking':.30},DLR:{'AI Capex & Data Center':.75,'Rates & Real Assets':.25},NVT:{'AI Capex & Data Center':.80,'Industrial Infrastructure':.20},VRT:{'AI Capex & Data Center':.90,'Industrial Infrastructure':.10},ETN:{'AI Capex & Data Center':.70,'Industrial Infrastructure':.30},FIX:{'AI Capex & Data Center':.75,'Industrial Infrastructure':.25},EME:{'AI Capex & Data Center':.75,'Industrial Infrastructure':.25},TER:{'AI Capex & Data Center':.70,'Semiconductor Cycle':.30},GEV:{'AI Capex & Data Center':.60,'Power Infrastructure':.40},PWR:{'AI Capex & Data Center':.70,'Power Infrastructure':.30},WTS:{'AI Capex & Data Center':.55,'Industrial Infrastructure':.45},
  MSTR:{'Digital Assets':1},COIN:{'Digital Assets':1},HOOD:{'Digital Assets':.65,'Retail Brokerage':.35},MARA:{'Digital Assets':1},RIOT:{'Digital Assets':1},CLSK:{'Digital Assets':1},IREN:{'Digital Assets':1},WULF:{'Digital Assets':1},HUT:{'Digital Assets':1},BTDR:{'Digital Assets':1},CIFR:{'Digital Assets':1},BITF:{'Digital Assets':1},RKLB:{'Space & Satellites':1},ASTS:{'Space & Satellites':1},RDW:{'Space & Satellites':1},BKSY:{'Space & Satellites':1},IRDM:{'Space & Satellites':1},IOVA:{Biotech:1},MRNA:{Biotech:1},RXRX:{Biotech:1},SDGR:{Biotech:1},CRSP:{Biotech:1},BEAM:{Biotech:1},VKTX:{Biotech:1},ALMS:{Biotech:1},HIMS:{Biotech:1},CGNX:{'Automation & Robotics':1},ROK:{'Automation & Robotics':1},SYM:{'Automation & Robotics':1},ISRG:{'Automation & Robotics':1},CRWD:{Cybersecurity:1},PANW:{Cybersecurity:1},NET:{Cybersecurity:1},ZS:{Cybersecurity:1},DDOG:{Cybersecurity:1},SNOW:{Cybersecurity:1},MDB:{Cybersecurity:1},CCJ:{'Nuclear & Baseload':1},UEC:{'Nuclear & Baseload':1},UUUU:{'Nuclear & Baseload':1},LEU:{'Nuclear & Baseload':1},BWXT:{'Nuclear & Baseload':1},SMR:{'Nuclear & Baseload':1},OKLO:{'Nuclear & Baseload':1},NNE:{'Nuclear & Baseload':1},NXE:{'Nuclear & Baseload':1},DNN:{'Nuclear & Baseload':1},CEG:{'Nuclear & Baseload':1},VST:{'Nuclear & Baseload':1},NRG:{'Nuclear & Baseload':1},TLN:{'Nuclear & Baseload':1}
};
const THEME_FACTOR={ai_compute:'AI Capex & Data Center',ai_networking:'AI Capex & Data Center',digital_infra:'AI Capex & Data Center',power:'Power Infrastructure',btc:'Digital Assets',space:'Space & Satellites',biotech:'Biotech',robotics:'Automation & Robotics',cybersecurity:'Cybersecurity',nuclear:'Nuclear & Baseload'};
const n=(v,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f};
const symbol=s=>String(s?.symbol||s?.ticker||'').toUpperCase();
const value=s=>n(s?.value,n(s?.shares)*n(s?.price||s?.currentPrice||s?.avgCost));
const isCash=s=>CASH.has(symbol(s));
const isCore=s=>String(s?.role||'Swing').toLowerCase()==='core';
const cleanWeights=w=>{const entries=Object.entries(w||{}).filter(([,v])=>n(v)>0),sum=entries.reduce((a,[,v])=>a+n(v),0);if(!sum)return{'Other':1};return Object.fromEntries(entries.map(([k,v])=>[k,n(v)/sum]));};
export function factorWeightsFor(s={}){const key=symbol(s);if(FACTOR_OVERRIDES[key])return cleanWeights(FACTOR_OVERRIDES[key]);const theme=String(s?.primaryTheme||s?.theme||'').trim(),themeKey=theme.toLowerCase().replace(/\s+/g,'_');if(THEME_FACTOR[themeKey])return{[THEME_FACTOR[themeKey]]:1};const text=`${s?.name||s?.companyName||''} ${s?.industry||''} ${s?.sector||''} ${s?.description||''} ${theme}`.toLowerCase();if(/data cent|hyperscal|ai infrastructure|server|semiconductor|memory chip|network equipment/.test(text))return{'AI Capex & Data Center':.75,'Technology Cycle':.25};if(/electrical|power management|power distribution|cooling|hvac|mechanical contractor/.test(text))return{'AI Capex & Data Center':.55,'Industrial Infrastructure':.45};if(/bitcoin|crypto|digital asset|blockchain/.test(text))return{'Digital Assets':1};if(/satellite|space launch|aerospace/.test(text))return{'Space & Satellites':1};if(/biotech|biopharma|therapeutic|drug discovery/.test(text))return{Biotech:1};if(/robot|machine vision|automation/.test(text))return{'Automation & Robotics':1};if(/cyber|security software|cloud security/.test(text))return{Cybersecurity:1};if(/nuclear|uranium/.test(text))return{'Nuclear & Baseload':1};return{[theme||'Other']:1};}
export function factorFor(s={}){const w=factorWeightsFor(s);return Object.entries(w).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Other';}
export function factorOverlap(a={},b={}){const wa=factorWeightsFor(a),wb=factorWeightsFor(b);return Object.keys(wa).reduce((sum,k)=>sum+Math.min(n(wa[k]),n(wb[k])),0);}
export function daysSince(date){if(!date)return null;const t=new Date(date).getTime();if(!Number.isFinite(t))return null;return Math.max(0,Math.floor((Date.now()-t)/86400000));}
export function swingTargetPct(action){return action==='Strong Buy'?.09:action==='Buy'?.06:0;}
export function signalPersistence(records=[],ticker='',lookbackDays=10){const key=String(ticker||'').toUpperCase(),cutoff=Date.now()-lookbackDays*86400000;const rows=(records||[]).filter(r=>String(r?.symbol||'').toUpperCase()===key&&['Buy','Strong Buy'].includes(r?.action)&&new Date(r?.timestamp||r?.day||0).getTime()>=cutoff);const days=[...new Set(rows.map(r=>String(r.day||r.timestamp||'').slice(0,10)).filter(Boolean))];const strongDays=[...new Set(rows.filter(r=>r.action==='Strong Buy').map(r=>String(r.day||r.timestamp||'').slice(0,10)).filter(Boolean))];return{actionableDays:days.length,strongDays:strongDays.length,persistent:strongDays.length>=1||days.length>=2};}
export function portfolioRiskSnapshot(rows=[]){const swingRows=rows.filter(r=>!isCash(r)&&!isCore(r)),coreRows=rows.filter(r=>!isCash(r)&&isCore(r));const swingInvested=swingRows.reduce((a,r)=>a+value(r),0),coreCapital=coreRows.reduce((a,r)=>a+value(r),0),cash=rows.filter(isCash).reduce((a,r)=>a+value(r),0),swingCapital=swingInvested+cash;const factors={};for(const r of swingRows){const v=value(r),weights=factorWeightsFor(r);for(const[f,w]of Object.entries(weights))factors[f]=(factors[f]||0)+v*w;}const factorPct=Object.fromEntries(Object.entries(factors).map(([k,v])=>[k,swingCapital?v/swingCapital:0]));const positions=Object.fromEntries(swingRows.map(r=>[symbol(r),{value:value(r),pctSwing:swingCapital?value(r)/swingCapital:0,factor:factorFor(r),factorWeights:factorWeightsFor(r)}]));const concentrations=Object.entries(factorPct).filter(([,p])=>p>.35).sort((a,b)=>b[1]-a[1]);return{swingCapital,swingInvested,coreCapital,cash,factors,factorPct,positions,concentrations};}
export function capitalAllowance({target={},action='Buy',requested=0,risk={}}={}){const ask=Math.max(0,n(requested)),swingCapital=n(risk.swingCapital),current=n(risk.positions?.[symbol(target)]?.value),weights=factorWeightsFor(target);if(!(ask>0&&swingCapital>0))return{amount:0,blocked:true,reason:'No Swing capital is available for sizing.'};const maxPositionPct=action==='Strong Buy'?.12:.08,maxFactorPct=action==='Strong Buy'?.35:.30,positionRoom=Math.max(0,swingCapital*maxPositionPct-current);let factorRoom=Infinity,bindingFactor='Other';for(const[f,w]of Object.entries(weights)){if(w<.20)continue;const existing=n(risk.factors?.[f]),room=(swingCapital*maxFactorPct-existing)/w;if(room<factorRoom){factorRoom=room;bindingFactor=f;}}if(!Number.isFinite(factorRoom))factorRoom=ask;factorRoom=Math.max(0,factorRoom);const amount=Math.min(ask,positionRoom,factorRoom),blocked=amount<Math.min(ask,750);let reason='Within portfolio risk budget.';if(positionRoom<=0)reason=`${symbol(target)} is already at or above its Swing position-risk ceiling.`;else if(factorRoom<=0)reason=`${bindingFactor} exposure is already at or above the portfolio factor ceiling.`;else if(amount<ask)reason=`Capital was reduced by the ${bindingFactor} factor or position-risk budget.`;const bindingWeight=n(weights[bindingFactor]),projectedFactorPct=swingCapital?(n(risk.factors?.[bindingFactor])+amount*bindingWeight)/swingCapital:0;return{amount,blocked,reason,maxPositionPct,maxFactorPct,factor:bindingFactor,factorWeights:weights,projectedPositionPct:(current+amount)/swingCapital,projectedFactorPct};}

// Judge the trade in percentage/risk terms first, then ask whether the approved whole-share
// position is large enough to matter to the Swing book. Nominal share price is never a penalty.
export function portfolioContributionGate({target={},approvedAmount=0,risk={},existingValue=0}={}){
  const swingCapital=n(risk?.swingCapital),pr=n(target?.price??target?.currentPrice??target?.lastPrice),amount=Math.max(0,n(approvedAmount)),shares=pr>0?Math.floor((amount+1e-6)/pr):0,invested=shares*pr;
  const rp=target?.riskPlan||target?.recommendation?.riskPlan||{},review=n(rp?.firstTrimPrice),invalidation=n(rp?.invalidationPrice),upsidePct=pr>0&&review>pr?(review/pr-1):0,downsidePct=pr>0&&invalidation>0&&invalidation<pr?(1-invalidation/pr):0,rewardRisk=downsidePct>0?upsidePct/downsidePct:null;
  const positionPct=swingCapital?invested/swingCapital:0,portfolioUpsidePct=swingCapital?invested*upsidePct/swingCapital:0,portfolioRiskPct=swingCapital?invested*downsidePct/swingCapital:0;
  const newPosition=n(existingValue)<=0,minPositionPct=.025,minContributionPct=.003;
  if(shares<1)return{pass:false,reason:'Approved capital cannot buy one whole share.',shares,invested,positionPct,upsidePct,downsidePct,rewardRisk,portfolioUpsidePct,portfolioRiskPct};
  if(!newPosition)return{pass:true,reason:'Existing position; contribution gate does not block incremental sizing.',shares,invested,positionPct,upsidePct,downsidePct,rewardRisk,portfolioUpsidePct,portfolioRiskPct};
  if(!(upsidePct>0&&downsidePct>0))return{pass:false,reason:'Hold cash — a new position needs a valid upside review and downside invalidation before funding.',shares,invested,positionPct,upsidePct,downsidePct,rewardRisk,portfolioUpsidePct,portfolioRiskPct};
  if(rewardRisk<2)return{pass:false,reason:`Hold cash — approved sizing has only ${rewardRisk.toFixed(1)}x reward/risk to the first review.`,shares,invested,positionPct,upsidePct,downsidePct,rewardRisk,portfolioUpsidePct,portfolioRiskPct};
  if(positionPct<minPositionPct&&portfolioUpsidePct<minContributionPct)return{pass:false,reason:`Hold cash — constraints leave only ${(positionPct*100).toFixed(1)}% of Swing capital and about ${(portfolioUpsidePct*100).toFixed(2)}% contribution to the first review.`,shares,invested,positionPct,upsidePct,downsidePct,rewardRisk,portfolioUpsidePct,portfolioRiskPct};
  return{pass:true,reason:`Portfolio-sized opportunity: ${(positionPct*100).toFixed(1)}% of Swing capital, ${(upsidePct*100).toFixed(1)}% to first review, ${rewardRisk.toFixed(1)}x reward/risk, about ${(portfolioUpsidePct*100).toFixed(2)}% Swing-book contribution.`,shares,invested,positionPct,upsidePct,downsidePct,rewardRisk,portfolioUpsidePct,portfolioRiskPct};
}
export function capitalSignalEligible({target={},action='Buy',persistence={}}={}){if(action==='Strong Buy')return{pass:true,reason:'Strong Buy may deploy immediately after hard qualification.'};if(action!=='Buy')return{pass:false,reason:'Not an actionable Buy.'};if(persistence?.persistent)return{pass:true,reason:'Buy has persisted across independent daily observations.'};return{pass:false,reason:'Hold cash — Buy quality is not yet persistent enough to fund.'};}
export function rotationGate({source={},target={},gap=0,persistence={},risk={},requested=0}={}){const action=String(target?.finalDecision?.action||target?.recommendation?.displayLabel||''),signal=capitalSignalEligible({target,action,persistence});if(!signal.pass)return{pass:false,reason:signal.reason};const daysHeld=daysSince(source?.openedAt),daysFromTrade=daysSince(source?.lastTradeAt||source?.openedAt),overlap=factorOverlap(source,target),sameFactor=overlap>=.50;const hurdle=daysFromTrade!==null&&daysFromTrade<10?55:daysHeld!==null&&daysHeld<25?50:45;if(n(gap)<hurdle)return{pass:false,reason:`Rotation edge ${Math.round(n(gap))} is below the ${hurdle}-point turnover-adjusted hurdle.`};if(overlap>=.35&&n(gap)<55)return{pass:false,reason:`Rotation has ${Math.round(overlap*100)}% factor overlap; require an exceptional edge before churning between correlated exposures.`};const allowance=capitalAllowance({target,action,requested,risk});if(allowance.blocked)return{pass:false,reason:allowance.reason,allowance};const contribution=portfolioContributionGate({target,approvedAmount:allowance.amount,risk,existingValue:n(risk.positions?.[symbol(target)]?.value)});if(!contribution.pass)return{pass:false,reason:contribution.reason,allowance,contribution};return{pass:true,reason:'Rotation clears persistence, turnover, overlap, concentration, and portfolio-contribution hurdles.',allowance,contribution,hurdle,sameFactor,factorOverlap:overlap};}
export function swingTimeReview(s={}){const held=daysSince(s?.openedAt),sinceTrade=daysSince(s?.lastTradeAt||s?.openedAt),pnl=n(s?.gainLossPct),e=s?.recommendation?.expertDecision||s?.expertDecision||{},m=e?.metrics||{},trade=n(e?.tradeSetupScore??s?.tradeSetupScore,50),technical=n(m?.technical??s?.technicalScore,50),momentum=n(m?.momentum??s?.momentumScore,50),leadership=n(m?.leadership??s?.relativeStrengthScore,50),capital=n(e?.capitalScore??s?.capitalScore??s?.finalDecision?.relativeCapitalScore,50);if(held===null)return{stage:'Unknown',held:null,sinceTrade,review:false,reason:'Holding-period clock is not available for this legacy position.'};if(held<10)return{stage:'Setup',held,sinceTrade,review:pnl<=-14,setupFailure:pnl<=-14,reason:pnl<=-14?'Early price damage is too large to ignore; re-underwrite the entry immediately.':'Initial setup window; avoid judging normal volatility too quickly.'};if(held<25){const weakFollow=trade<60||technical<55||momentum<55||leadership<55||capital<62,proofFailure=pnl<=-10||(pnl<=-7&&weakFollow)||(held>=15&&pnl<=1&&weakFollow);return{stage:'Proof',held,sinceTrade,review:proofFailure,proofFailure,reason:proofFailure?'The swing has not delivered enough follow-through for its age; re-underwrite the entry thesis now.':'The swing should begin proving relative strength and setup quality.'};}if(held<45)return{stage:'Re-underwrite',held,sinceTrade,review:(pnl<=-10)||(pnl<=0&&(trade<58||technical<55||momentum<52||capital<62)),reason:'Flat/losing capital must re-earn its place as the holding period matures.'};if(held<60)return{stage:'Opportunity Cost',held,sinceTrade,review:pnl<=5&&(trade<60||leadership<55||capital<62),reason:'Opportunity cost is now material; continuation requires affirmative evidence.'};return{stage:'Long Swing Review',held,sinceTrade,review:pnl<=8||trade<60,reason:'A 60+ day Swing must be explicitly re-underwritten rather than held by inertia.'};}