// Existing-position review for Swing holdings.
// Passive Hold is not a default: aging/losing capital must re-earn its place.
// Material imminent catalysts may defer a marginal exit, but never rescue a severely broken trade.

const n=(v,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f};
const sym=s=>String(s?.symbol||s?.ticker||'').toUpperCase();
function metrics(s={}){const e=s?.recommendation?.expertDecision||s?.expertDecision||{},m=e?.metrics||{};return{thesis:n(e?.thesisScore??s?.thesisScore,50),trade:n(e?.tradeSetupScore??s?.tradeSetupScore,50),capital:n(e?.capitalScore??s?.capitalScore??s?.finalDecision?.relativeCapitalScore,50),technical:n(m?.technical??s?.technicalScore,50),momentum:n(m?.momentum??s?.momentumScore,50),leadership:n(m?.leadership??s?.relativeStrengthScore,50),risk:n(m?.risk??s?.riskScore,50)};}
function factorWeaknessFlag(stock={}){const raw=[stock?.factorState,stock?.themeState,stock?.sectorState,stock?.marketCycleState,stock?.recommendation?.factorState,stock?.recommendation?.themeState].filter(Boolean).join(' ').toLowerCase();return stock?.factorWeakness===true||stock?.themeWeakness===true||stock?.sectorWeakness===true||/(weak|lag|deteriorat|risk-off|declin|bear)/.test(raw);}
function exitDiagnosis({stock={},m={},held=null,opportunityCost=false}={}){if(opportunityCost||(held!==null&&held>=45))return 'OPPORTUNITY COST';const factorWeak=factorWeaknessFlag(stock),nameWeak=m.trade<58||m.technical<55||m.momentum<52||m.leadership<55||m.capital<62;if(factorWeak&&nameWeak)return 'BOTH — FACTOR + NAME WEAKNESS';if(factorWeak)return 'FACTOR WEAKNESS';return 'NAME / TRADE WEAKNESS';}
function exitReason(label,text){return `Exit diagnosis: ${label}. ${text}`;}
function imminentCatalyst(stock={}){const rows=Array.isArray(stock?.materialCatalysts)?stock.materialCatalysts:[];return rows.find(x=>x?.material&&n(x?.days,99)<=1)||null;}
function catalystHold(catalyst,held,pnl,status='Catalyst Review'){return{override:true,action:'Hold',reason:`Material catalyst review: ${catalyst.label}. ${catalyst.detail} The position is currently ${pnl<0?'down ':'up '}${Math.abs(pnl).toFixed(1)}% after ${held} days. Defer a marginal lifecycle exit until the first post-event market read; this is a short evidence window, not permission to average down or ignore further deterioration.`,status,catalystDeferredExit:true,materialCatalyst:catalyst,held};}
function catalystRejectedText(catalyst,thresholdLabel){return catalyst?` ${catalyst.label} was explicitly considered, but it does not override this exit because ${thresholdLabel}.`:'';}
export function reunderwriteExistingPosition({stock={},decision={},risk={},timeReview={}}={}){
  const key=sym(stock),action=decision?.action||'Hold';
  if(String(stock?.role||'Swing').toLowerCase()==='core')return{override:false,action,reason:decision?.reason||''};
  if(key==='IRDM'&&!['Cash','Exit','Rotate','Trim'].includes(action)){const pr=n(stock?.price??stock?.currentPrice??stock?.lastPrice),held=timeReview?.held==null?null:n(timeReview.held),notionalValue=54,cashComponent=27,grossNotionalSpreadPct=pr>0?(notionalValue/pr-1)*100:null;return{override:true,action:'Hold',reason:`Acquisition pending — do not treat IRDM as a normal Swing or add on ordinary technical signals. The announced deal has a $54 notional value ($27 cash plus RKLB stock subject to a collar) and is expected to close in mid-2027. ${grossNotionalSpreadPct===null?'Evaluate the merger spread, closing risk, and opportunity cost versus cash/qualified replacements.':`At the current price the simple notional spread is about ${grossNotionalSpreadPct.toFixed(1)}%, before time-to-close, RKLB collar exposure, and deal-break risk.`}`,status:'Acquisition Pending',held,specialSituation:{type:'Acquisition Pending',buyer:'RKLB',notionalValue,cashComponent,expectedClose:'mid-2027',blockNewCapital:true,grossNotionalSpreadPct}};}
  if(['Cash','Exit','Rotate','Trim','Add'].includes(action))return{override:false,action,reason:decision?.reason||''};if(action!=='Hold')return{override:false,action:action||'Review',reason:decision?.reason||''};
  const pos=risk?.positions?.[key]||{},pctSwing=n(pos?.pctSwing),pnl=n(stock?.gainLossPct),m=metrics(stock),weights=pos?.factorWeights||{},held=timeReview?.held==null?null:n(timeReview.held),catalyst=imminentCatalyst(stock);
  let crowdedFactor='',crowdedPct=0,weightedCrowding=0;for(const[f,wRaw]of Object.entries(weights)){const w=n(wRaw),p=n(risk?.factorPct?.[f]);if(w>=.20&&p>crowdedPct){crowdedPct=p;crowdedFactor=f;}weightedCrowding+=w*p;}
  const concentrated=crowdedPct>.35,oversized=pctSwing>=.15,veryOversized=pctSwing>=.20,losing=pnl<=-7,doubleDigitLoss=pnl<=-10,setupFailureLoss=pnl<=-12,deepLoss=pnl<=-14,severeLoss=pnl<=-18;
  const weakForward=m.trade<58||m.technical<55||m.momentum<52||m.leadership<55||m.capital<62,broadWeak=m.trade<52&&m.technical<52&&m.momentum<50&&m.leadership<52,brokenForward=m.trade<45&&m.technical<45&&m.momentum<42&&m.leadership<45&&m.thesis<58,strongForward=m.trade>=65&&m.technical>=60&&m.momentum>=58&&m.leadership>=58&&m.capital>=68;
  const aging=held!==null&&held>=28,stale=held!==null&&held>=42,veryStale=held!==null&&held>=60,deadMoney=aging&&pnl<=2&&weakForward,opportunityCost=stale&&pnl<=5&&(m.trade<60||m.momentum<55||m.leadership<55),setupStage=held!==null&&held<10,proofStage=held!==null&&held>=10&&held<25,reunderwriteStage=held!==null&&held>=25&&held<45,opportunityStage=held!==null&&held>=45,matureReview=Boolean(timeReview?.review),reviewPoints=[veryOversized,oversized&&concentrated,doubleDigitLoss,concentrated&&losing,weakForward,matureReview,deadMoney,opportunityCost].filter(Boolean).length,proofFailure=proofStage&&Boolean(timeReview?.proofFailure||matureReview),diagnosis=()=>exitDiagnosis({stock,m,held,opportunityCost});

  if(setupStage&&setupFailureLoss){if(!strongForward){const catalystText=catalystRejectedText(catalyst,`the position is already down ${Math.abs(pnl).toFixed(1)}% inside the first 10 days, beyond the 12% Setup-risk threshold`);return{override:true,action:'Exit',reason:exitReason(diagnosis(),`Only ${held} days into Setup, the trade is down ${Math.abs(pnl).toFixed(1)}% without exceptional forward evidence. The entry thesis has failed its early risk test.${catalystText}`),status:'Setup Failure',exitDiagnosis:diagnosis(),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,setupFailure:true,catalystConsidered:Boolean(catalyst),catalystDeferredExit:false,materialCatalyst:catalyst||null};}return{override:true,action:'Hold',reason:`Hold only under immediate risk review: ${held} days into Setup and already down ${Math.abs(pnl).toFixed(1)}%. Strong forward evidence prevents an automatic exit, but the position must stabilize now.${catalyst?` ${catalyst.label} is noted, but the Hold is earned by unusually strong position-level evidence rather than by the catalyst.`:''}`,status:'Immediate Risk Review',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,catalystConsidered:Boolean(catalyst),materialCatalyst:catalyst||null};}
  if(proofFailure){if(doubleDigitLoss&&!strongForward){if(catalyst&&!deepLoss&&!brokenForward)return{...catalystHold(catalyst,held,pnl,'Proof Catalyst Review'),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,proofFailure:true};return{override:true,action:'Exit',reason:exitReason(diagnosis(),`The trade has failed Proof — ${held} days in and down ${Math.abs(pnl).toFixed(1)}% without enough setup, momentum, leadership, and capital quality to justify more time.${catalystRejectedText(catalyst,deepLoss?'the drawdown has reached the severe-loss threshold':'the forward evidence is already broken')}`),status:'Proof Failure Exit',exitDiagnosis:diagnosis(),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,proofFailure:true,catalystConsidered:Boolean(catalyst),catalystDeferredExit:false,materialCatalyst:catalyst||null};}if(doubleDigitLoss)return{override:true,action:'Hold',reason:`Hold only under immediate Proof review: ${held} days in and down ${Math.abs(pnl).toFixed(1)}%. Forward evidence is still unusually strong, but a double-digit drawdown cannot remain an ordinary Hold. Require prompt stabilization or exit.`,status:'Proof Failure Review',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,proofFailure:true};return{override:true,action:'Hold',reason:`Hold only conditionally: ${held} days in, the trade has not produced enough follow-through. Require improving setup/momentum/relative strength now or recycle the capital.`,status:'Proof Failure Review',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,proofFailure:true};}
  if(reunderwriteStage&&pnl<=-10&&weakForward){if(catalyst&&!deepLoss&&!brokenForward)return{...catalystHold(catalyst,held,pnl,'Re-underwrite Catalyst Review'),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m};return{override:true,action:'Exit',reason:exitReason(diagnosis(),`${held} days in, this Swing is still down ${Math.abs(pnl).toFixed(1)}% and forward evidence is weak. The position has failed re-underwriting; recycle the capital to cash or a qualified opportunity.${catalystRejectedText(catalyst,deepLoss?'the drawdown has reached the severe-loss threshold':'the forward evidence is already broken')}`),status:'Re-underwrite Exit',exitDiagnosis:diagnosis(),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,opportunityCost:true,catalystConsidered:Boolean(catalyst),catalystDeferredExit:false,materialCatalyst:catalyst||null};}
  if(opportunityStage&&pnl<=-5&&weakForward){if(catalyst&&!deepLoss&&!brokenForward)return{...catalystHold(catalyst,held,pnl,'Opportunity-Cost Catalyst Review'),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,opportunityCost:true};return{override:true,action:'Exit',reason:exitReason('OPPORTUNITY COST',`${held} days in, this Swing remains down ${Math.abs(pnl).toFixed(1)}% with weak forward evidence. Cash now has the stronger claim on this capital; no replacement hurdle is required to stop carrying dead money.${catalystRejectedText(catalyst,deepLoss?'the drawdown has reached the severe-loss threshold':'the forward evidence is already broken')}`),status:'Opportunity Cost Exit',exitDiagnosis:'OPPORTUNITY COST',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,opportunityCost:true,catalystConsidered:Boolean(catalyst),catalystDeferredExit:false,materialCatalyst:catalyst||null};}
  const capitalReview=reviewPoints>=3||(veryOversized&&concentrated&&weakForward)||(doubleDigitLoss&&concentrated&&weakForward)||opportunityCost;
  if(capitalReview){if((severeLoss||veryStale||matureReview)&&brokenForward)return{override:true,action:'Exit',reason:exitReason(diagnosis(),`The forward thesis/setup no longer earns the capital.${catalystRejectedText(catalyst,'the position-level evidence is already broken')}`),status:'Exit',exitDiagnosis:diagnosis(),pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,opportunityCost:true,catalystConsidered:Boolean(catalyst),catalystDeferredExit:false,materialCatalyst:catalyst||null};const reduce=(oversized&&concentrated&&doubleDigitLoss&&weakForward)||(opportunityCost&&oversized&&weakForward);if(reduce){const targetPct=.10,targetValue=n(risk?.swingCapital)*targetPct,currentValue=n(pos?.value),reduceValue=Math.max(0,currentValue-targetValue),pr=n(stock?.price??stock?.currentPrice??stock?.lastPrice),reduceShares=pr>0?Math.max(1,Math.floor(reduceValue/pr)):0;return{override:true,action:'Reduce',reason:opportunityCost?'Reduce: this aging Swing is tying up too much capital without enough forward strength.':'Reduce: this Swing is too large while its factor is crowded and relative strength is weak.',status:'Reduce',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,targetPct,reduceValue,reduceShares,held,opportunityCost};}if(opportunityCost)return{override:true,action:'Hold',reason:`Hold only conditionally: ${held} days in, this position must improve soon or give way to cash/a clearly superior qualified opportunity.`,status:'Opportunity Cost Hold',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held,opportunityCost:true};return{override:true,action:'Hold',reason:'Hold, but no add: forward evidence does not justify more risk.',status:'Conditional Hold',pctSwing,crowdedFactor,crowdedPct,weightedCrowding,metrics:m,held};}
  const positives=[];if(m.thesis>=65)positives.push('thesis');if(m.trade>=60)positives.push('setup');if(m.leadership>=60)positives.push('leadership');if(m.technical>=58)positives.push('technicals');if(deadMoney)return{override:true,action:'Hold',reason:`Hold only conditionally: ${held} days in and little progress. Require improving setup/relative strength or redeploy to cash/a superior qualified opportunity.`,status:'Opportunity Cost Hold',metrics:m,held,opportunityCost:true};if(!positives.length&&broadWeak)return{override:true,action:'Hold',reason:'Hold for now, but no add: forward evidence is weak.',status:'Conditional Hold',metrics:m,held};if(positives.length)return{override:true,action:'Hold',reason:`Hold: ${positives.join(', ')} remain supportive.${concentrated?' No add while this factor is over the portfolio limit.':' Add only if it independently clears the fresh-capital standard.'}`,status:'Conviction Hold',pctSwing,crowdedFactor,crowdedPct,metrics:m,held};return{override:true,action:'Hold',reason:'Hold for now, but no add: the evidence is mixed.',status:'Conditional Hold',pctSwing,crowdedFactor,crowdedPct,metrics:m,held};
}
