export const RELEASE_MANIFEST={
  release:"2026-08-25-hardening",
  baselineCommit:"5cbb82f",
  canonicalProject:"screener-app-cq5t",
  features:[
    "market-cycle-overhaul",
    "portfolio-sync",
    "open-date-tracking",
    "special-situations",
    "stage-badges",
    "cash-display",
    "material-event-overrides",
    "capital-score-opportunity-gap",
    "replacement-edge",
    "proof-followthrough",
    "portfolio-action-summary",
    "fmp-fundamentals-fallback",
    "winner-lifecycle",
    "swing-time-review-logic"
  ]
};
